### ISSUE TITLE
Linux 报错

### ISSUE THREAD

**Issue by xgdgsc** [doraemonkeys/WindSend#23]
Linux rust服务端可以编译,运行时有输出错误
```
thread 'tokio-runtime-worker' panicked at /home/sgao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtk-0.18.1/src/rt.rs:122:9:
Attempted to initialize GTK from two different threads.
```
安卓端可以粘贴,不能复制:
![Screenshot_20240227_151400](https://github.com/doraemonkeys/WindSend/assets/1189869/b5e1f9d4-6def-489a-a827-44fdd96c9e0b)

flutter linux端运行的时候也有错

建议可以搞个linux虚拟机测试下

**Comment by xgdgsc** [comment]
另外 `cargo build  --release --target x86_64-unknown-linux-musl` 报:

```
warning: cairo-sys-rs@0.18.2: pkg-config has not been configured to support cross-compilation.

error: failed to run custom build command for `cairo-sys-rs v0.18.2`

Caused by:
  process didn't exit successfully: `/data/Documents/oss/WindSend/windSend-rs/target/release/build/cairo-sys-rs-ee413c2dafb3d680/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=CAIRO_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_x86_64-unknown-linux-musl
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_x86_64_unknown_linux_musl
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-musl
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_musl
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-musl
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_musl
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=pkg-config has not been configured to support cross-compilation.

  Install a sysroot for the target platform and configure it via
  PKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a
  cross-compiling wrapper for pkg-config and set it via
  PKG_CONFIG environment variable.
```
如果不要桌面那些特性是不是可以出个纯服务端的版本支持musl部署更方便

**Comment by doraemonkeys** [comment]
> Linux rust服务端可以编译,运行时有输出错误
> 
> ```
> thread 'tokio-runtime-worker' panicked at /home/sgao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtk-0.18.1/src/rt.rs:122:9:
> Attempted to initialize GTK from two different threads.
> ```
> 
> 安卓端可以粘贴,不能复制: ![Screenshot_20240227_151400](https://private-user-images.githubusercontent.com/1189869/308071749-b5e1f9d4-6def-489a-a827-44fdd96c9e0b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjEzNDIsIm5iZiI6MTcwOTAyMTA0MiwicGF0aCI6Ii8xMTg5ODY5LzMwODA3MTc0OS1iNWUxZjlkNC02ZGVmLTQ4OWEtYTgyNy00NGZkZDk2YzllMGIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMDgwNDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODU4ZTRlOGQ2ZGEwZmZmMWQ5ZjkyMDA4NjcxYTJlN2EyODI2YjgxM2Y3N2M1ZjgzM2NhNDQ3YTU0MDI0ODliNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IfJdjHexIbKUCH68SXFPM0zohnJuEOi5Ck3XUY-_b2M)
> 
> flutter linux端运行的时候也有错
> 
> 建议可以搞个linux虚拟机测试下

panic可能是tray-icon crate的bug，在我的Ubuntu虚拟机上不会panic但是系统托盘基本用不了

**Comment by doraemonkeys** [comment]
> 另外 `cargo build --release --target x86_64-unknown-linux-musl` 报:
> 
> ```
> warning: cairo-sys-rs@0.18.2: pkg-config has not been configured to support cross-compilation.
> 
> error: failed to run custom build command for `cairo-sys-rs v0.18.2`
> 
> Caused by:
>   process didn't exit successfully: `/data/Documents/oss/WindSend/windSend-rs/target/release/build/cairo-sys-rs-ee413c2dafb3d680/build-script-build` (exit status: 1)
>   --- stdout
>   cargo:rerun-if-env-changed=CAIRO_NO_PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_x86_64-unknown-linux-musl
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_x86_64_unknown_linux_musl
>   cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-musl
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_musl
>   cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-musl
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_musl
>   cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
>   cargo:warning=pkg-config has not been configured to support cross-compilation.
> 
>   Install a sysroot for the target platform and configure it via
>   PKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a
>   cross-compiling wrapper for pkg-config and set it via
>   PKG_CONFIG environment variable.
> ```
> 
> 如果不要桌面那些特性是不是可以出个纯服务端的版本支持musl部署更方便

不要系统托盘界面的支持可以去除很多依赖，应该是可以出一个纯服务端的版本的。也不知道剪切板的库能不能做linux-musl的编译

**Comment by xgdgsc** [comment]
没有panic退出,就是输出错误,托盘也能显示和使用

**Comment by doraemonkeys** [comment]
> 错误

我这里没有报错，有更详细的错误输出吗

**Comment by xgdgsc** [comment]
点复制的时候报
```
➜  release git:(main) RUST_BACKTRACE=full ./wind_send
thread '<unnamed>' panicked at src/main.rs:79:10:
bind error: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
stack backtrace:
   0:     0x56053e41caa6 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x56053e41caa6 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56053e41caa6 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x56053e41caa6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x56053e44c9e0 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x56053e44c9e0 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x56053e4191cf - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x56053e41c884 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x56053e41c884 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x56053e41e107 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x56053e41de69 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x56053e41e598 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x56053e41e472 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  13:     0x56053e41cfa6 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x56053e41e1d0 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x56053da99b75 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x56053da9a0c3 - core::result::unwrap_failed::h03d8a5018196e1cd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
  17:     0x56053db9537a - tokio::runtime::park::CachedParkThread::block_on::h7844550278e867e6
  18:     0x56053db025ba - tokio::runtime::context::runtime::enter_runtime::hf3783856db9d6458
  19:     0x56053dae36ee - tokio::runtime::runtime::Runtime::block_on::h13eedf8571fd0fed
  20:     0x56053db8c7af - std::sys_common::backtrace::__rust_begin_short_backtrace::h9876793df3a4421c
  21:     0x56053dba7d71 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h48c66d34c44d9b71
  22:     0x56053e423bf5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h12de4fc57affb195
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  23:     0x56053e423bf5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3c619f45059d5cf1
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  24:     0x56053e423bf5 - std::sys::unix::thread::Thread::new::thread_start::hbac657605e4b7389
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/unix/thread.rs:108:17
  25:     0x7f8781f99ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  26:     0x7f878202b850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  27:                0x0 - <unknown>

```

**Comment by xgdgsc** [comment]
手机上点复制的时候报
```
 RUST_BACKTRACE=full ./wind_send
thread 'tokio-runtime-worker' panicked at /home/sgao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtk-0.18.1/src/rt.rs:122:9:
Attempted to initialize GTK from two different threads.
stack backtrace:
   0:     0x55db8b958aa6 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x55db8b958aa6 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55db8b958aa6 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55db8b958aa6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55db8b9889e0 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x55db8b9889e0 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x55db8b9551cf - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x55db8b958884 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55db8b958884 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55db8b95a107 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x55db8b959e69 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x55db8b95a598 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x55db8b95a439 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:649:13
  13:     0x55db8b958fa6 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x55db8b95a1d0 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x55db8afd5b75 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x55db8b5f60d2 - gtk::rt::init::h452e11c66392e935
  17:     0x55db8b2330e9 - clipboard_files::read::h0fbe646df2c0f529
  18:     0x55db8afe5536 - wind_send::route::copy::copy_handler::{{closure}}::h9e2cb6367386fa00
  19:     0x55db8aff5086 - wind_send::route::route::main_process::{{closure}}::h1bf5f4583901a668
  20:     0x55db8afe0641 - tokio::runtime::task::core::Core<T,S>::poll::he39c2c1acd80b4c0
  21:     0x55db8b0a36ee - tokio::runtime::task::harness::Harness<T,S>::poll::h3e1812b72a089516
  22:     0x55db8b601b9f - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h6c87555d26061bad
  23:     0x55db8b601013 - tokio::runtime::scheduler::multi_thread::worker::Context::run::hf9f4ec85780aa302
  24:     0x55db8b607767 - tokio::runtime::context::scoped::Scoped<T>::set::h6dd686647e926e48
  25:     0x55db8b60756f - tokio::runtime::context::runtime::enter_runtime::ha231d744c996deef
  26:     0x55db8b600538 - tokio::runtime::scheduler::multi_thread::worker::run::h63b06428f50d199a
  27:     0x55db8b5fde33 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::heb5c9f3256f33387
  28:     0x55db8b60e7b7 - tokio::runtime::task::core::Core<T,S>::poll::h55a896a7aa94ea96
  29:     0x55db8b5fae0a - tokio::runtime::task::harness::Harness<T,S>::poll::h8c2eed741b74db5a
  30:     0x55db8b61e6d0 - tokio::runtime::blocking::pool::Inner::run::h5d9ef9308df7e66f
  31:     0x55db8b60d1c7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h64acfaa7070a77e6
  32:     0x55db8b619af9 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h04391611bb7bb3ff
  33:     0x55db8b95fbf5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h12de4fc57affb195
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  34:     0x55db8b95fbf5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3c619f45059d5cf1
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  35:     0x55db8b95fbf5 - std::sys::unix::thread::Thread::new::thread_start::hbac657605e4b7389
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/unix/thread.rs:108:17
  36:     0x7f44cde09ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  37:     0x7f44cde9b850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  38:                0x0 - <unknown>
```

**Comment by doraemonkeys** [comment]
@xgdgsc 修复了

**Comment by xgdgsc** [comment]
确实可以
